"""create ambis schema

Revision ID: 554a024e01a9
Revises:
Create Date: 2026-09-13

Near-verbatim transcription of AMBIS_DB_Schema_Seed_Example.sql PART 1
(D:\\ooka\\dev\\hack\\AMBIS_DB_Schema_Seed_Example.sql, lines 24-310) — the
authoritative DDL for the AMBIS.IN schema. RLS policies, the updated_at
trigger, the HNSW vector index, and the deferred sessions.path_node_id FK
have no clean SQLAlchemy ORM equivalent, so this migration is raw SQL rather
than autogenerated; the hand-written models in app/models/ are a second,
manually-synced representation kept in step with this file.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "554a024e01a9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------- extensions ----------
    op.execute(sa.text("create extension if not exists pgcrypto"))
    op.execute(sa.text("create extension if not exists vector"))

    # ---------- 1.1 Identity ----------
    op.execute(
        sa.text(
            """
            create table if not exists profiles (
              id           uuid primary key references auth.users(id) on delete cascade,
              display_name text not null,
              grade        smallint default 7,
              created_at   timestamptz default now()
            )
            """
        )
    )

    # ---------- 1.2 Curriculum (static — seeded, not student-writable) ----------
    op.execute(
        sa.text(
            """
            create table if not exists subjects (
              id   uuid primary key default gen_random_uuid(),
              code text unique not null,
              name text not null
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists units (
              id         uuid primary key default gen_random_uuid(),
              subject_id uuid not null references subjects(id) on delete cascade,
              name       text not null,
              position   int not null default 0
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists concepts (
              id          uuid primary key default gen_random_uuid(),
              unit_id     uuid not null references units(id) on delete cascade,
              code        text unique not null,
              name        text not null,
              description text,
              position    int not null default 0
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists concept_prerequisites (
              concept_id      uuid not null references concepts(id) on delete cascade,
              prerequisite_id uuid not null references concepts(id) on delete cascade,
              primary key (concept_id, prerequisite_id),
              check (concept_id <> prerequisite_id)
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists misconceptions (
              id               uuid primary key default gen_random_uuid(),
              concept_id       uuid not null references concepts(id) on delete cascade,
              code             text unique not null,
              description      text not null,
              remediation_hint text
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists exercises (
              id             uuid primary key default gen_random_uuid(),
              concept_id     uuid not null references concepts(id) on delete cascade,
              difficulty     smallint not null check (difficulty between 1 and 5),
              kind           text not null check (kind in ('mcq','short_answer','steps')),
              is_diagnostic  boolean not null default false,
              question       text not null,
              options        jsonb,
              correct_answer text not null,
              solution_steps jsonb,
              metadata       jsonb not null default '{}'::jsonb
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists curriculum_chunks (
              id         uuid primary key default gen_random_uuid(),
              concept_id uuid not null references concepts(id) on delete cascade,
              content    text not null,
              embedding  vector(768),
              metadata   jsonb not null default '{}'::jsonb
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create index if not exists curriculum_chunks_embedding_idx
              on curriculum_chunks using hnsw (embedding vector_cosine_ops)
            """
        )
    )

    # ---------- 1.3 Learning runtime (shared by Ask + Learning Path) ----------
    op.execute(
        sa.text(
            """
            create table if not exists sessions (
              id           uuid primary key default gen_random_uuid(),
              student_id   uuid not null references profiles(id) on delete cascade,
              mode         text not null check (mode in ('ask','learning_path','diagnostic')),
              path_node_id uuid,
              status       text not null default 'active' check (status in ('active','ended')),
              started_at   timestamptz default now(),
              ended_at     timestamptz
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists messages (
              id         uuid primary key default gen_random_uuid(),
              session_id uuid not null references sessions(id) on delete cascade,
              role       text not null check (role in ('student','agent','system')),
              content    text not null,
              metadata   jsonb not null default '{}'::jsonb,
              created_at timestamptz default now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists problems (
              id           uuid primary key default gen_random_uuid(),
              session_id   uuid not null references sessions(id) on delete cascade,
              concept_id   uuid not null references concepts(id),
              source       text not null check (source in ('exercise','ad_hoc')),
              exercise_id  uuid references exercises(id),
              problem_text text,
              metadata     jsonb not null default '{}'::jsonb,
              created_at   timestamptz default now(),
              check (
                (source = 'exercise' and exercise_id is not null and problem_text is null) or
                (source = 'ad_hoc'   and exercise_id is null and problem_text is not null)
              )
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists attempts (
              id                         uuid primary key default gen_random_uuid(),
              problem_id                 uuid not null references problems(id) on delete cascade,
              session_id                 uuid not null references sessions(id) on delete cascade,
              student_id                 uuid not null references profiles(id) on delete cascade,
              concept_id                 uuid not null references concepts(id),
              attempt_number             smallint not null default 1,
              student_answer             text,
              is_correct                 boolean,
              error_type                 text check (error_type in ('calculation','procedural','conceptual','prerequisite')),
              detected_misconception_id  uuid references misconceptions(id),
              hints_used                 smallint not null default 0,
              time_spent_ms              int,
              created_at                 timestamptz default now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists interventions (
              id         uuid primary key default gen_random_uuid(),
              session_id uuid not null references sessions(id) on delete cascade,
              student_id uuid not null references profiles(id) on delete cascade,
              concept_id uuid not null references concepts(id),
              attempt_id uuid references attempts(id),
              kind       text not null check (kind in
                ('hint','guiding_question','explanation','worked_example',
                 'easier_exercise','prerequisite_review','difficulty_up')),
              rule_code  text,
              reason     text,
              content    jsonb,
              created_at timestamptz default now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists student_concept_state (
              student_id           uuid not null references profiles(id) on delete cascade,
              concept_id           uuid not null references concepts(id) on delete cascade,
              mastery              real not null default 0,
              confidence           real not null default 0,
              total_attempts       int not null default 0,
              correct_streak       int not null default 0,
              misconception_counts jsonb not null default '{}'::jsonb,
              last_seen_at         timestamptz,
              updated_at           timestamptz default now(),
              primary key (student_id, concept_id)
            )
            """
        )
    )

    # ---------- 1.4 Learning Path mode ----------
    op.execute(
        sa.text(
            """
            create table if not exists learning_paths (
              id                    uuid primary key default gen_random_uuid(),
              student_id            uuid not null references profiles(id) on delete cascade,
              subject_id            uuid not null references subjects(id),
              target_concept_id     uuid not null references concepts(id),
              difficulty_preference smallint check (difficulty_preference between 1 and 5),
              goal_text             text,
              status                text not null default 'active' check (status in ('active','completed','abandoned')),
              diagnostic_session_id uuid references sessions(id),
              created_at            timestamptz default now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            create table if not exists path_nodes (
              id                uuid primary key default gen_random_uuid(),
              path_id           uuid not null references learning_paths(id) on delete cascade,
              position          int not null,
              node_type         text not null check (node_type in ('lesson','practice','checkpoint','remediation')),
              concept_id        uuid not null references concepts(id),
              status            text not null default 'locked' check (status in ('locked','available','in_progress','done','skipped')),
              adaptation_reason text,
              created_at        timestamptz default now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            """
            do $$
            begin
              if not exists (
                select 1 from pg_constraint where conname = 'sessions_path_node_id_fkey'
              ) then
                alter table sessions
                  add constraint sessions_path_node_id_fkey
                  foreign key (path_node_id) references path_nodes(id) on delete set null;
              end if;
            end $$
            """
        )
    )

    # ---------- 1.5 Indexes ----------
    op.execute(sa.text("create index if not exists idx_problems_session on problems(session_id)"))
    op.execute(sa.text("create index if not exists idx_attempts_student_concept on attempts(student_id, concept_id)"))
    op.execute(sa.text("create index if not exists idx_attempts_session on attempts(session_id)"))
    op.execute(sa.text("create index if not exists idx_attempts_problem on attempts(problem_id)"))
    op.execute(sa.text("create index if not exists idx_interventions_session on interventions(session_id)"))
    op.execute(sa.text("create index if not exists idx_path_nodes_path on path_nodes(path_id, position)"))
    op.execute(sa.text("create index if not exists idx_messages_session on messages(session_id)"))

    # ---------- 1.6 updated_at trigger for the snapshot table ----------
    op.execute(
        sa.text(
            """
            create or replace function set_updated_at() returns trigger as $$
            begin
              new.updated_at = now();
              return new;
            end;
            $$ language plpgsql
            """
        )
    )
    op.execute(sa.text("drop trigger if exists trg_student_concept_state_updated on student_concept_state"))
    op.execute(
        sa.text(
            """
            create trigger trg_student_concept_state_updated
              before update on student_concept_state
              for each row execute function set_updated_at()
            """
        )
    )

    # ---------- 1.7 Row Level Security ----------
    op.execute(sa.text("alter table profiles enable row level security"))
    op.execute(sa.text("alter table sessions enable row level security"))
    op.execute(sa.text("alter table messages enable row level security"))
    op.execute(sa.text("alter table problems enable row level security"))
    op.execute(sa.text("alter table attempts enable row level security"))
    op.execute(sa.text("alter table interventions enable row level security"))
    op.execute(sa.text("alter table student_concept_state enable row level security"))
    op.execute(sa.text("alter table learning_paths enable row level security"))
    op.execute(sa.text("alter table path_nodes enable row level security"))

    op.execute(sa.text('drop policy if exists "own profile" on profiles'))
    op.execute(sa.text('create policy "own profile" on profiles for select using (id = auth.uid())'))

    op.execute(sa.text('drop policy if exists "own sessions" on sessions'))
    op.execute(sa.text('create policy "own sessions" on sessions for all using (student_id = auth.uid())'))

    op.execute(sa.text('drop policy if exists "own messages" on messages'))
    op.execute(
        sa.text(
            """
            create policy "own messages" on messages for all using (
              session_id in (select id from sessions where student_id = auth.uid())
            )
            """
        )
    )

    op.execute(sa.text('drop policy if exists "own problems" on problems'))
    op.execute(
        sa.text(
            """
            create policy "own problems" on problems for all using (
              session_id in (select id from sessions where student_id = auth.uid())
            )
            """
        )
    )

    op.execute(sa.text('drop policy if exists "own attempts" on attempts'))
    op.execute(sa.text('create policy "own attempts" on attempts for all using (student_id = auth.uid())'))

    op.execute(sa.text('drop policy if exists "own interventions" on interventions'))
    op.execute(
        sa.text('create policy "own interventions" on interventions for all using (student_id = auth.uid())')
    )

    op.execute(sa.text('drop policy if exists "own state" on student_concept_state'))
    op.execute(
        sa.text('create policy "own state" on student_concept_state for all using (student_id = auth.uid())')
    )

    op.execute(sa.text('drop policy if exists "own paths" on learning_paths'))
    op.execute(sa.text('create policy "own paths" on learning_paths for all using (student_id = auth.uid())'))

    op.execute(sa.text('drop policy if exists "own path nodes" on path_nodes'))
    op.execute(
        sa.text(
            """
            create policy "own path nodes" on path_nodes for all using (
              path_id in (select id from learning_paths where student_id = auth.uid())
            )
            """
        )
    )

    # curriculum tables: public read, writes restricted to service role
    # (no policy = only service role bypasses RLS)
    op.execute(sa.text("alter table subjects enable row level security"))
    op.execute(sa.text("alter table units enable row level security"))
    op.execute(sa.text("alter table concepts enable row level security"))
    op.execute(sa.text("alter table concept_prerequisites enable row level security"))
    op.execute(sa.text("alter table misconceptions enable row level security"))
    op.execute(sa.text("alter table exercises enable row level security"))
    op.execute(sa.text("alter table curriculum_chunks enable row level security"))

    op.execute(sa.text('drop policy if exists "public read subjects" on subjects'))
    op.execute(sa.text('create policy "public read subjects" on subjects for select using (true)'))
    op.execute(sa.text('drop policy if exists "public read units" on units'))
    op.execute(sa.text('create policy "public read units" on units for select using (true)'))
    op.execute(sa.text('drop policy if exists "public read concepts" on concepts'))
    op.execute(sa.text('create policy "public read concepts" on concepts for select using (true)'))
    op.execute(sa.text('drop policy if exists "public read prereqs" on concept_prerequisites'))
    op.execute(sa.text('create policy "public read prereqs" on concept_prerequisites for select using (true)'))
    op.execute(sa.text('drop policy if exists "public read misconceptions" on misconceptions'))
    op.execute(sa.text('create policy "public read misconceptions" on misconceptions for select using (true)'))
    op.execute(sa.text('drop policy if exists "public read exercises" on exercises'))
    op.execute(sa.text('create policy "public read exercises" on exercises for select using (true)'))
    op.execute(sa.text('drop policy if exists "public read chunks" on curriculum_chunks'))
    op.execute(sa.text('create policy "public read chunks" on curriculum_chunks for select using (true)'))


def downgrade() -> None:
    for stmt in [
        "drop table if exists path_nodes",
        "drop table if exists learning_paths",
        "drop table if exists student_concept_state",
        "drop table if exists interventions",
        "drop table if exists attempts",
        "drop table if exists problems",
        "drop table if exists messages",
        "drop table if exists sessions",
        "drop table if exists curriculum_chunks",
        "drop table if exists exercises",
        "drop table if exists misconceptions",
        "drop table if exists concept_prerequisites",
        "drop table if exists concepts",
        "drop table if exists units",
        "drop table if exists subjects",
        "drop table if exists profiles",
        "drop function if exists set_updated_at() cascade",
    ]:
        op.execute(sa.text(stmt))
